<% proxy_vars = {} %>
<% %w(http_proxy https_proxy no_proxy).each do |envvar| %>
<%   if ENV.key?(envvar) %>
<%     proxy_vars[envvar] = ENV[envvar] %>
<%   end %>
<% end %>
---
driver:
  name: vagrant
  customize:
    memory: 512
  network:
    - ["forwarded_port", { guest: 3000, host: 3000, auto_correct: true }]

<% if proxy_vars.size > 0 %>
driver_config:
<% %w(http_proxy https_proxy no_proxy).each do |envvar| %>
<% if ENV.key?(envvar) %>
  <%= envvar %>: '<%= ENV[envvar] %>'
<% end %>
<% end %>

<% end %>

provisioner:
  name: chef_zero
  client_rb:
<% %w(http_proxy https_proxy no_proxy).each do |envvar| %>
<% if ENV.key?(envvar) %>
    <%= envvar %>: '<%= ENV[envvar] %>'
<% end %>
<% end %>

platforms:
  - name: centos-6.6
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[grafana2::default]
